name: build-book
on:
  pull_request:

jobs:
  setup-conda-environment:
    uses: ./.github/setup-environment.yaml
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Build the book
        run: |
          jupyter-book build notebooks/
      - name: Zip the book
        run: |
          set -x
          set -e
          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip notebooks/_build/html
      - name: Upload zipped book artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-zip
          path: ./book.zip
