name: build-book
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: radar-cookbook-dev
          use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: /usr/share/miniconda3/envs/radar-cookbook-dev
          key: linux-64-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: mamba env update -n radar-cookbook-dev -f environment.yml

      - name: Build the book
        run: |
          jupyter-book build notebooks/
      - name: Zip the book
        run: |
          set -x
          set -e
          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip notebooks/_build/html
      - name: Upload zipped book artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-zip
          path: ./book.zip
