name: build-book
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: radar-cookbook-dev
          auto-update-conda: false
          python-version: 3.8
          environment-file: environment.yml
          mamba-version: '*'
          use-mamba: true

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build notebooks/

      - name: Zip-book
        run: |
          set -x
          set -e
          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip notebooks/_build/html
      - uses: actions/upload-artifact@v3
        with:
          name: book-zip
          path: ./book.zip
