name: deploy-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *' # Daily “At 00:00”

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: github.repository == 'ProjectPythiaTutorials/radar-cookbook'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      # Install dependencies
      - uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: radar-cookbook-dev
          auto-update-conda: false
          python-version: 3.8
          environment-file: environment.yml
          mamba-version: '*'
          use-mamba: true
      # Build the book
      - name: Build the book
        run: |
          jupyter-book build notebooks/
      - name: Zip-book
        run: |
          set -x
          set -e

          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip notebooks/_build/html

      - uses: actions/upload-artifact@v3
        with:
          name: book-zip
          path: ./book.zip

      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: notebooks/_build/html
