name: deploy-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

jobs:
  build:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: .
    secrets:
      ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
      ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Download Artifact Book
        uses: actions/download-artifact@v3
        with:
          name: book-zip-${{ github.event.number }}

      - name: Unzip the book
        run: |
          rm -rf _build/html
          unzip book.zip
          rm -f book.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          keep_files: true  # This preserves existing previews from open PRs
