name: deploy-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/build-book.yaml
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: notebooks/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Download Artifact Book
        uses: dawidd6/action-download-artifact@v2.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-book.yaml
          commit: ${{ github.sha }}
          name: book-zip-${{ github.event.number }}

      - name: Unzip the book
        run: |
          rm -rf notebooks/_build/html
          unzip book.zip
          rm -f book.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: notebooks/_build/html
          keep_files: true  # This preserves existing previews from open PRs
