name: link-checker

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Name of conda environment to activate'
        required: true
        type: string
      environment_file:
        description: 'Name of conda environment file'
        required: false
        default: 'environment.yml'
        type: string
      path_to_notebooks:
        description: 'Location of the JupyterBook source relative to repo root'
        required: false
        default: './'

jobs:
  link-checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: ${{ inputs.environment_name }}
          use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: /usr/share/miniconda3/envs/${{ inputs.environment_name }}
          key: linux-64-conda-${{ hashFiles('${{ inputs.environment_file }}') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: mamba env update -n ${{ inputs.environment_name }} -f ${{ inputs.environment_file }}

      - name: Disable notebook execution
        shell: python
        run: |
          import yaml
          with open('${{ inputs.path_to_notebooks }}/_config.yml') as f:
            data = yaml.safe_load(f)
          data['execute']['execute_notebooks'] = 'off'
          with open('${{ inputs.path_to_notebooks }}/_config.yml', 'w') as f:
            yaml.dump(data, f)
      - name: Check external links
        run: |
          jupyter-book build --builder linkcheck ${{ inputs.path_to_notebooks }}
