name: preview-book
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: radar-cookbook-dev
          auto-update-conda: false
          python-version: 3.8
          environment-file: environment.yml
          mamba-version: '*'
          use-mamba: true

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build notebooks/
      # Push the book's HTML to github-pages
      # This will be published at /_preview/PRnumber/ relative to the main site
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
          destination_dir: _preview/${{github.event.number}}
