name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    secrets:
      ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
      ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: ./

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
  