name: secret-book-build
on:
  workflow_run:
    workflows:
      - trigger-book-build
    types:
      - completed
env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

jobs:
  find-pull-request:
    uses: ProjectPythia/cookbook-actions/.github/workflows/find-pull-request.yaml@main

  build:
    needs: find-pull-request
    if: github.event.workflow_run.conclusion == 'success'
    uses: brian-rose/cookbook-actions/.github/workflows/build-book.yaml@secrets
    secrets:
      ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
      ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
    with:
      environment_name: radar-cookbook-dev
      artifact_name: book-zip-${{ needs.find-pull-request.outputs.number }}
      code_artifact_name: code-zip-${{ needs.find-pull-request.outputs.number }}
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
