name: trigger-link-check
on:
  pull_request:

jobs:
  link-check:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/link-checker.yaml@main
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: ./
      use_cached_environment: 'true'
      