name: trigger-book-build
on:
  pull_request:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  build:
    uses: ProjectPythiaTutorials/radar-cookbook/.github/build-book.yaml@main
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: notebooks/
  link-check:
    uses: ProjectPythiaTutorials/radar-cookbook/.github/link-checker.yaml@main
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: notebooks/
