name: trigger-book-build
on:
  pull_request:
  workflow_call:
    secrets:
      ARM_USERNAME:
        required: true
      ARM_PASSWORD:
        required: true
env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

jobs:
  build:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/build-book.yaml@main
    secrets:
      ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
      ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: "."
      use_cached_environment: 'false'  # This is default, not strickly needed. Set to 'false' to always build a new environment
  link-check:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/link-checker.yaml@main
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: "."
      use_cached_environment: 'true'
