name: trigger-book-build
on:
  pull_request:
env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

jobs:
  build:
    steps:
      - name: Build the Book
        uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/build-book.yaml@main
        with:
          environment_name: radar-cookbook-dev
          environment_file: environment.yml
          path_to_notebooks: .
          use_cached_environment: 'false'
        env:
          ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
          ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
  link-check:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/link-checker.yaml@main
    with:
      environment_name: radar-cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: "."
      use_cached_environment: 'true'
